restore_yarn_cache:
  steps:
    - restore_cache:
        key: &YARN_LOCK_CACHE_KEY yarn-lock-v6-{{ checksum "ui/yarn.lock" }}
save_yarn_cache:
  steps:
    - save_cache:
        key: *YARN_LOCK_CACHE_KEY
        paths:
          - ui/node_modules
