executor: docker-env-go-test
parallelism: 8
steps:
  - check-branch-name
  - checkout
  - go_test:
      log_dir: "/tmp/testlogs"
  - store_artifacts:
      path: test-results
  - store_test_results:
      path: test-results
  - store_artifacts:
      path: "/tmp/testlogs"
